package fr.formation.inti.entity;


//Generated 6 mai 2021 � 13:26:26 by Hibernate Tools 5.1.10.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
* Department generated by hbm2java
*/
@Entity
@Table(name = "department")
public class Department{

	private Integer deptId;
	private String name;

	public Department() {
	}

	public Department(String name) {
		this.name = name;
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "DEPT_ID", unique = true, nullable = false)
	public Integer getDeptId() {
		return this.deptId;
	}

	public void setDeptId(Integer deptId) {
		this.deptId = deptId;
	}

	@Column(name = "NAME", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	

	@Override
	public String toString() {
		return "Department [deptId=" + deptId + ", name=" + name + "]";
	}

	
	
}